language: csharp
solution: cloudscribe.Syndication.sln
sudo: false
dist: xenial
mono: none
dotnet: 3.0.100
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
os:
  - linux
 
script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - dotnet build -c Release
