dist: trusty
language: csharp
install: true
mono: none
dotnet: 2.0.0
sudo: required
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
    
script:
  - ./build.sh
  
cache:
  directories:
    - tools

