dist: trusty
language: csharp
install: true
mono: latest
dotnet: 2.1.101
sudo: required
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

before_install:
  - chmod +x build.sh
    
script:
  - ./build.sh
  
cache:
  directories:
    - tools

